file(
  STRINGS "${CMAKE_CURRENT_SOURCE_DIR}/vscge/include/vscge/version.h" VSCGE_VERSION_PARTS
  REGEX "#define VSCGE_VERSION_[A-Z]+[ ]+"
)

string(
  REGEX REPLACE ".+VSCGE_VERSION_MAJOR[ ]+([0-9]+).*"
  "\\1" VSCGE_VERSION_MAJOR
  "${VSCGE_VERSION_PARTS}")
string(
  REGEX REPLACE ".+VSCGE_VERSION_MINOR[ ]+([0-9]+).*"
  "\\1" VSCGE_VERSION_MINOR
  "${VSCGE_VERSION_PARTS}"
)
string(
  REGEX REPLACE ".+VSCGE_VERSION_PATCH[ ]+([0-9]+).*"
  "\\1" VSCGE_VERSION_PATCH
  "${VSCGE_VERSION_PARTS}"
)

set(VSCGE_VERSION "${VSCGE_VERSION_MAJOR}.${VSCGE_VERSION_MINOR}.${VSCGE_VERSION_PATCH}")